#!/bin/bash

mongo angulartpdvis-dev --eval "db.incidents.drop()"

mongoimport --port 27017 --db angulartpdvis-dev --type csv --file incidents.csv --collection incidents --fields PRIMARYKEY,INCI_ID,CALL_ID,ADDRESS_PUBLIC,DATE_REPT,HOUR_REPT,DATE_OCCU,HOUR_OCCU,DATE_FND,HOUR_FND,NEIGHBORHD,AGENCY,OFFENSE,STATUTDESC,CAPRIORITY,NATURECODE,NatureCodeDesc,HOWRECEIVE,CSDISPOSIT,CSDISPDESC,ACTDATE,ACTTIME,EMDIVISION,EMUNIT,X,Y,ADDUSER,APPSTATE,ADDTIME,LOC_METHOD,ADD_NS,ADD_DIR_NS,ADD_EW,ADD_DIR_EW,NHA_NAME
